# Numpy
Numpy is a *numerical python* which is used to deal with array or matrix and it's methods
It is installed using pip and the command is `pip install numpy`

In [2]:
print("Hello World")

Hello World


In [3]:
print("Namaste")

Namaste


In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

## Arrays vs Python lists

In [6]:
# python list
list_example = [1, "Hello", 2, 3.5, 4,5]

#numpy array
array_example = np.array([1,2,3,4,5], dtype=np.int32)

In [7]:
array_example

array([1, 2, 3, 4, 5], dtype=int32)

In [8]:
array_example = np.array([1,"Hello", 2,3,4,5])
#yesma hamile data type ndeko bhayera integer haru chai was changed to string

In [9]:
array_example

array(['1', 'Hello', '2', '3', '4', '5'], dtype='<U21')

## Arrays and array consturction

In [10]:
# one dimenstional array i.e 1*3 matrix banxa
a = np.array([1,2,3])
print(a)

[1 2 3]


In [11]:
print( type(a), "\n","Shape: ", a.shape, "\n", "Indexed elements:", a[0], a[1], a[2])

<class 'numpy.ndarray'> 
 Shape:  (3,) 
 Indexed elements: 1 2 3


### More dimensions in array

In [12]:
b = np.array([[1,2],[3,4]])
# Yesle chai euta 2*2 ko matrix banayo i.e 2D, first row chai 1,2 hunxa ani second row chai 3,4 

In [13]:
b.shape

(2, 2)

In [14]:
b

array([[1, 2],
       [3, 4]])

In [15]:
c = np.array([[1,2],[3,4],[5,6]])

In [16]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
d = np.array([[[1,2], [3,4], [5,6], [7,8]]])
# yo cahi euta 3D array banyo

In [18]:
d

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [19]:
b.ndim

2

In [20]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [21]:
print(b.shape)

(2, 2, 2)


In [22]:
b.ndim

3

## Array indexing

In [23]:
#1D array ko lagi normal list jastai indexing ho
#2D array ko indexing example: array[row,column]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [24]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
# Use slicing to pull out subarray consisting of the first 2 rows
b = a[:2]

In [26]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
# Use slicing to pull out subarray consisting of the first 2 rows and columns 1 and 2
c = a[:2, 1:3]
c

array([[2, 3],
       [6, 7]])

In [28]:
# Get this output: 
# [[5,6]
#  [9, 10]]
d = a [1:3, :2]
d

array([[ 5,  6],
       [ 9, 10]])

## Initializing values in array

### Ones 

In [29]:
a = np.ones(3)
a

array([1., 1., 1.])

In [30]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
c = np.ones((4,3,2))
c

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### Constant array 

In [32]:
a = np.full((3),2)
a

array([2, 2, 2])

In [33]:
b = np.full((3,2),7)
b

array([[7, 7],
       [7, 7],
       [7, 7]])

### Random value

In [34]:
a = np.random.random(3)
a

array([0.80067935, 0.64932021, 0.03890216])

### Identity matrix

In [35]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [36]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Stacking of array

In [37]:
#vertical stack
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# horizontal stacking
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [39]:
# arko horizontal stacking
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

## Array math 

In [40]:
a = np.random.random(10000)
a

array([0.5695405 , 0.91471355, 0.92921159, ..., 0.4051434 , 0.80923839,
       0.09868033])

In [41]:
%%time
x = np.sum(a)
x

CPU times: user 619 μs, sys: 95 μs, total: 714 μs
Wall time: 769 μs


np.float64(4953.117314278965)

In [42]:
%%time 
x = 0
for element in a:
    x = x+element

CPU times: user 10.3 ms, sys: 0 ns, total: 10.3 ms
Wall time: 12.2 ms


In [43]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[8,9]])

In [44]:
# Addition  
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [11 13]]
[[ 6  8]
 [11 13]]


In [46]:
# Subtraction 
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-5 -5]]
[[-4 -4]
 [-5 -5]]


In [47]:
# multiplication (element wise)
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [24 36]]
[[ 5 12]
 [24 36]]


In [48]:
# elementwise division
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.375      0.44444444]]
[[0.2        0.33333333]
 [0.375      0.44444444]]


In [50]:
# elementwise square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### Dot product

In [52]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[8,9]])

v = np.array([9,10])
w = np.array([11,12])

print(v.dot(w))
print(np.dot(v,w))

219
219


In [54]:
# Practical example of dot product

features = np.array([1500, 3, 10])
weights = np.array([100,5000, -2000])

predicted_price = np.dot(features,weights)

print(f"The predicted price is ${predicted_price}")

The predicted price is $145000


In [56]:
preds = np.array([0.2, 0.5, 0.92, 0.9, 0.1])
to_predict_class = ["apple", "banana", "ball", "mango","orange"]

predicted_class_index = np.argmax(preds)
predicted_class = to_predict_class[predicted_class_index]
print(predicted_class)

possible_class_index = np.where(preds > 0.85)[0]
print(possible_class_index)

ball
[2 3]


### argmax (index of maximum element in array)
### argmin (index of minimum element in array)
### argsort(get soted list of indices, by element value, in ascending order)
### where (get indicies of elements that meet some condition)

In [57]:
a = np.array([1, 8, 9, -3, 2, 4, 7, 9])

In [58]:
print(np.argmax(a))

2


In [59]:
print(np.argmin(a))

3


In [60]:
print(np.argsort(a))

[3 0 4 5 6 1 2 7]


In [61]:
# reverse nikalna 
print(np.argsort(a)[::-1])

[7 2 1 6 5 4 0 3]


In [64]:
print(np.where(a>5)[0])

print(np.where(a>= a[np.argmax(a)])[0])

[1 2 6 7]
[2 7]


### max: Maximum value dinxa
### min: minimum value dinxa
### sum: Sum dinxa

In [66]:
x = np.array([[1,2], [3,4], [5,6]])

In [67]:
print(np.max(x))
print(np.min(x))
print(np.sum(x))

6
1
21


In [71]:
x = np.array([[1,2,8], [5,3,1], [4,6,5]])
print(x)

[[1 2 8]
 [5 3 1]
 [4 6 5]]


In [72]:
print(np.max(x, axis = 0)) # compute max of each column

[5 6 8]


In [73]:
print(np.max(x, axis = 1)) #compute minimum of each row 

[8 5 6]


### Transnpose 

In [74]:
ary = np.array([1,2])
print(ary)

[1 2]


In [75]:
ary.T

array([1, 2])

In [76]:
x = np.array([[1,2], [3,4], [5,6]])
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [77]:
x.T

array([[1, 3, 5],
       [2, 4, 6]])

### Reshape

In [78]:
data = np.array([1,2,3,4,5,6,7,8])
print(data)

[1 2 3 4 5 6 7 8]


In [79]:
data.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
data.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [84]:
w = np.array([[1], [2], [3]])
print(w)
w.shape

[[1]
 [2]
 [3]]


(3, 1)

In [83]:
# removing unnecessary dimensions
y = w.reshape(-1,)
print(y)
y.shape

[1 2 3]


(3,)

In [86]:
# removind dimensio using squeeze
w = np.array([[1], [2], [3]])
print(w.ndim)
squeezedw = np.squeeze(w)
print(squeezedw.ndim)

2
1


In [89]:
# Adding dimension
y = np.array([1,2,3])
print(y.ndim)

y = y.reshape(-1,1)
print(y.ndim)
print(y)

1
2
[[1]
 [2]
 [3]]
